# import = ["/home/chief/.config/alacritty/base16/tomorrow-night.toml"]
# import = ["/home/chief/.config/alacritty/alduin.toml"]
import = ["/home/chief/.config/alacritty/base16/black-metal.toml"]

[shell]
program = "/usr/bin/bash"

[cursor.style]
shape = "beam"

[font]
size = 12.0

[font.normal]
family = "Cascadia Code NF"

[window]
dynamic_title = true

[window.dimensions]
columns = 80
lines = 24
